// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: wm_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel_s1;
lv_obj_t * ui_panel_water_level;
lv_obj_t * ui_Dropdown_water_level;
lv_obj_t * ui_Label11;
void ui_event_panel_rins(lv_event_t * e);
lv_obj_t * ui_panel_rins;
lv_obj_t * ui_Dropdown_rins;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Roller_programs;
void ui_event_panel_water_temp(lv_event_t * e);
lv_obj_t * ui_panel_water_temp;
lv_obj_t * ui_Dropdown_water_temp;
lv_obj_t * ui_Label3;
lv_obj_t * ui_panel_washtime;
lv_obj_t * ui_Dropdown_washtime;
lv_obj_t * ui_Label12;
lv_obj_t * ui_panel_superspin;
lv_obj_t * ui_Dropdown_superspin;
lv_obj_t * ui_Label14;
lv_obj_t * ui_panel_spin;
lv_obj_t * ui_Dropdown_spin;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label_timer_s1;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_ImageIconS1;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panel_s2;
lv_obj_t * ui_ImageIconS2;
lv_obj_t * ui_Label_timer_s2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label9;
lv_obj_t * ui_PanelRins;
lv_obj_t * ui_LabelRinsS2;
lv_obj_t * ui_RollerRinsS2;
lv_obj_t * ui_PanelWaterTemp6;
lv_obj_t * ui_LabelTimeS2;
lv_obj_t * ui_RollerTimeS2;
lv_obj_t * ui_PanelWaterTemp7;
lv_obj_t * ui_LabelSuperSpinS2;
lv_obj_t * ui_RollerSuperSpinS2;
lv_obj_t * ui_PanelWaterTemp8;
lv_obj_t * ui_LabelTempS2;
lv_obj_t * ui_RollerTempS2;
lv_obj_t * ui_PanelLevelS2;
lv_obj_t * ui_LabelLevelS2;
lv_obj_t * ui_RollerLevelS2;
lv_obj_t * ui_PanelSpin;
lv_obj_t * ui_LabelSpinS2;
lv_obj_t * ui_RollerSpinS2;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Panel_s3;
void ui_event_PanelDelayS3(lv_event_t * e);
lv_obj_t * ui_PanelDelayS3;
lv_obj_t * ui_LabelDelayS3;
lv_obj_t * ui_RollerDelayS3;
lv_obj_t * ui_PanelSoakS3;
lv_obj_t * ui_LabelSoakS3;
lv_obj_t * ui_RollerSoakS3;
void ui_event_PanelIronS3(lv_event_t * e);
lv_obj_t * ui_PanelIronS3;
lv_obj_t * ui_LabelIronS3;
lv_obj_t * ui_RollerIronS3;
void ui_event_PanelTubS3(lv_event_t * e);
lv_obj_t * ui_PanelTubS3;
lv_obj_t * ui_LabelTubS3;
lv_obj_t * ui_RollerTubS3;
lv_obj_t * ui_ImageIcons3;
lv_obj_t * ui_Label_timer_s3;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label16;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label15;
lv_obj_t * ui____initial_actions0;

const char g_str_programs[] = "NORMAL\nHEAVY\nQUICK\nBLANKET\nSENSITIVE\nFRAGRANCE";
const char g_str_waterTemp[] = "Cold\nWarm\nHot";
const char g_str_waterLevel[] = "LEVEL 1\nLEVEL 2\nLEVEL 3\nLEVEL 4\n";
const char g_str_washTime[] = "8 MIN\n10 MIN\n12 MIN\n16 MIN\n18 MIN";
extern const char g_str_rins[] = "1 TIME\n2 TIMES\n3 TIMES\n4 TIMES";
extern const char g_str_spin[] = "3 MIN\n5 MIN\n9 MIN";
extern const char g_str_superSpin[] = "10 MIN\n15 MIN\n30 MIN";

lv_obj_t * ui_label_control_s1;
lv_obj_t * ui_label_controlArabic_s1;
lv_obj_t * ui_label_control_s2;
lv_obj_t * ui_label_controlArabic_s2;
lv_obj_t * ui_label_control_s3;
lv_obj_t * ui_label_controlArabic_s3;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_panel_rins(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Dropdown_rins, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_panel_water_temp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Dropdown_water_temp, LV_STATE_PRESSED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 500, 0);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_PanelDelayS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_y(ui_PanelDelayS3, -10);
        lv_obj_set_y(ui_LabelDelayS3, -50);
        lv_obj_set_y(ui_RollerDelayS3, 10);
        lv_obj_set_height(ui_PanelDelayS3, 130);
        lv_obj_add_flag(ui_PanelSoakS3, LV_OBJ_FLAG_HIDDEN);
        lv_roller_set_visible_row_count(ui_RollerDelayS3, 3);
        lv_obj_set_style_text_font(ui_RollerDelayS3, &ui_font_montbold_22, LV_PART_SELECTED);
        lv_obj_set_style_text_font(ui_RollerDelayS3, &ui_font_mont_bold_16, LV_PART_MAIN);
        lv_obj_set_style_text_color(ui_RollerDelayS3, lv_color_hex(0xedeff1), LV_PART_MAIN|LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_RollerDelayS3, lv_color_hex(0xedeff1), LV_PART_SELECTED|LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelDelayS3, lv_color_hex(0x384d5e), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelDelayS3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        lv_obj_set_y(ui_PanelDelayS3, -50);
        lv_obj_set_y(ui_LabelDelayS3, 14);
        lv_obj_set_y(ui_RollerDelayS3, -7);

        lv_obj_set_height(ui_PanelDelayS3, 55);
        lv_obj_clear_flag(ui_PanelSoakS3, LV_OBJ_FLAG_HIDDEN);
        lv_roller_set_visible_row_count(ui_RollerDelayS3, 1);
        lv_obj_set_style_text_font(ui_RollerDelayS3, &ui_font_montregular16, LV_PART_SELECTED);
        lv_obj_set_style_text_color(ui_RollerDelayS3, lv_color_hex(0x6497B1), LV_PART_SELECTED|LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelDelayS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelDelayS3, LV_TEXT_DECOR_NONE, LV_PART_MAIN);
    }
}

void ui_event_PanelSoakS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_y(ui_PanelSoakS3, -10);
        lv_obj_set_y(ui_LabelSoakS3, -50);
        lv_obj_set_y(ui_RollerSoakS3, 10);
        lv_obj_set_height(ui_PanelSoakS3, 130);
        lv_obj_add_flag(ui_PanelDelayS3, LV_OBJ_FLAG_HIDDEN);
        lv_roller_set_visible_row_count(ui_RollerSoakS3, 3);
        lv_obj_set_style_text_font(ui_RollerSoakS3, &ui_font_montbold_22, LV_PART_SELECTED);
        lv_obj_set_style_text_font(ui_RollerSoakS3, &ui_font_mont_bold_16, LV_PART_MAIN);
        lv_obj_set_style_text_color(ui_RollerSoakS3, lv_color_hex(0xedeff1), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_RollerSoakS3, lv_color_hex(0xedeff1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelSoakS3, lv_color_hex(0x384d5e), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelSoakS3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN);
    }
    else if (event_code == LV_EVENT_DEFOCUSED)
    {
        lv_obj_set_y(ui_PanelSoakS3, 24);
        lv_obj_set_y(ui_LabelSoakS3, 14);
        lv_obj_set_y(ui_RollerSoakS3, -7);

        lv_obj_set_height(ui_PanelSoakS3, 55);
        lv_obj_clear_flag(ui_PanelDelayS3, LV_OBJ_FLAG_HIDDEN);

        lv_roller_set_visible_row_count(ui_RollerSoakS3, 1);
        lv_obj_set_style_text_font(ui_RollerSoakS3, &ui_font_montregular16, LV_PART_SELECTED);

        lv_obj_set_style_text_color(ui_RollerSoakS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelSoakS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelSoakS3, LV_TEXT_DECOR_NONE, LV_PART_MAIN);
    }
}


void ui_event_PanelTubS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_y(ui_PanelTubS3, -10);
        lv_obj_set_y(ui_LabelTubS3, -50);
        lv_obj_set_y(ui_RollerTubS3, 10);
        lv_obj_set_height(ui_PanelTubS3, 130);
        lv_obj_add_flag(ui_PanelIronS3, LV_OBJ_FLAG_HIDDEN);
        lv_roller_set_visible_row_count(ui_RollerTubS3, 3);
        lv_obj_set_style_text_font(ui_RollerTubS3, &ui_font_montbold_22, LV_PART_SELECTED);
        lv_obj_set_style_text_font(ui_RollerTubS3, &ui_font_mont_bold_16, LV_PART_MAIN);
        lv_obj_set_style_text_color(ui_RollerTubS3, lv_color_hex(0xedeff1), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_RollerTubS3, lv_color_hex(0xedeff1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelTubS3, lv_color_hex(0x384d5e), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelTubS3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN);
    }
    else if (event_code == LV_EVENT_DEFOCUSED)
    {
        lv_obj_set_y(ui_PanelTubS3, -50);
        lv_obj_set_y(ui_LabelTubS3, 14);
        lv_obj_set_y(ui_RollerTubS3, -7);

        lv_obj_set_height(ui_PanelTubS3, 55);
        lv_obj_clear_flag(ui_PanelIronS3, LV_OBJ_FLAG_HIDDEN);

        lv_roller_set_visible_row_count(ui_RollerTubS3, 1);
        lv_obj_set_style_text_font(ui_RollerTubS3, &ui_font_montregular16, LV_PART_SELECTED);

        lv_obj_set_style_text_color(ui_RollerTubS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelTubS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelTubS3, LV_TEXT_DECOR_NONE, LV_PART_MAIN);
    }
}


void ui_event_PanelIronS3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_y(ui_PanelIronS3, -10);
        lv_obj_set_y(ui_LabelIronS3, -50);
        lv_obj_set_y(ui_RollerIronS3, 10);
        lv_obj_set_height(ui_PanelIronS3, 130);
        lv_obj_add_flag(ui_PanelTubS3, LV_OBJ_FLAG_HIDDEN);
        lv_roller_set_visible_row_count(ui_RollerIronS3, 3);
        lv_obj_set_style_text_font(ui_RollerIronS3, &ui_font_montbold_22, LV_PART_SELECTED);
        lv_obj_set_style_text_font(ui_RollerIronS3, &ui_font_mont_bold_16, LV_PART_MAIN);
        lv_obj_set_style_text_color(ui_RollerIronS3, lv_color_hex(0xedeff1), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_RollerIronS3, lv_color_hex(0xedeff1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelIronS3, lv_color_hex(0x384d5e), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelIronS3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN);
    }
    else if (event_code == LV_EVENT_DEFOCUSED)
    {
        lv_obj_set_y(ui_PanelIronS3, 24);
        lv_obj_set_y(ui_LabelIronS3, 14);
        lv_obj_set_y(ui_RollerIronS3, -7);

        lv_obj_set_height(ui_PanelIronS3, 55);
        lv_obj_clear_flag(ui_PanelTubS3, LV_OBJ_FLAG_HIDDEN);

        lv_roller_set_visible_row_count(ui_RollerIronS3, 1);
        lv_obj_set_style_text_font(ui_RollerIronS3, &ui_font_montregular16, LV_PART_SELECTED);

        lv_obj_set_style_text_color(ui_RollerIronS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_PanelIronS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_decor(ui_LabelIronS3, LV_TEXT_DECOR_NONE, LV_PART_MAIN);
    }
}

typedef struct {
    uint8_t water_temp;
    uint8_t rins;
    uint8_t washtime;
    uint8_t waterlevel;
    uint8_t spin;
    uint8_t superspin;
}program_options_t;


program_options_t default_options[] =
{
    //temp rins  washtime spin level sspin
    {1,    1,    3,       1,   1,    0},  //Normal
    {1,    3,    4,       2,   3,    2},  //HEAVY
    {1,    1,    1,       0,   0,    0},  //Quick
    {0,    1,    2,       2,   3,    0},  //BLANKET
    {1,    2,    1,       0,   0,    0},  //DELICATE
    {1,    2,    3,       2,   2,    1}   //FRAGRANCE
};


void ui_event_roller_programs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    char str[10];
    if(event_code == LV_EVENT_VALUE_CHANGED) 
    {
        //Screen1
        uint16_t selected = lv_roller_get_selected(target);
        lv_dropdown_set_selected(ui_Dropdown_rins, default_options[selected].rins);
        lv_dropdown_set_selected(ui_Dropdown_superspin, default_options[selected].superspin);
        lv_dropdown_set_selected(ui_Dropdown_spin, default_options[selected].spin);
        lv_dropdown_set_selected(ui_Dropdown_water_temp, default_options[selected].water_temp);
        lv_dropdown_set_selected(ui_Dropdown_washtime, default_options[selected].washtime);
        lv_dropdown_set_selected(ui_Dropdown_water_level, default_options[selected].waterlevel);
        //screen2
        lv_roller_set_selected(ui_RollerRinsS2, default_options[selected].rins, LV_ANIM_OFF);
        lv_roller_set_selected(ui_RollerSuperSpinS2, default_options[selected].superspin, LV_ANIM_OFF);
        lv_roller_set_selected(ui_RollerSpinS2, default_options[selected].spin, LV_ANIM_OFF);
        lv_roller_set_selected(ui_RollerTempS2, default_options[selected].water_temp, LV_ANIM_OFF);
        lv_roller_set_selected(ui_RollerTimeS2, default_options[selected].washtime, LV_ANIM_OFF);
        lv_roller_set_selected(ui_RollerLevelS2, default_options[selected].waterlevel, LV_ANIM_OFF);

    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t* dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    

}

