// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: wm_ui

#ifndef _WM_UI_UI_H
#define _WM_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel_s1;
extern lv_obj_t * ui_panel_water_level;
extern lv_obj_t * ui_Dropdown_water_level;
extern lv_obj_t * ui_Label11;
void ui_event_panel_rins(lv_event_t * e);
extern lv_obj_t * ui_panel_rins;
extern lv_obj_t * ui_Dropdown_rins;
extern lv_obj_t * ui_Label5;
void ui_event_roller_programs(lv_event_t * e);
extern lv_obj_t * ui_Roller_programs;
void ui_event_panel_water_temp(lv_event_t * e);
extern lv_obj_t * ui_panel_water_temp;
extern lv_obj_t * ui_Dropdown_water_temp;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_panel_washtime;
extern lv_obj_t * ui_Dropdown_washtime;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_panel_superspin;
extern lv_obj_t * ui_Dropdown_superspin;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_panel_spin;
extern lv_obj_t * ui_Dropdown_spin;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label_timer_s1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ImageIconS1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel_s2;
extern lv_obj_t * ui_ImageIconS2;
extern lv_obj_t * ui_Label_timer_s2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_PanelRins;
extern lv_obj_t * ui_LabelRinsS2;
extern lv_obj_t * ui_RollerRinsS2;
extern lv_obj_t * ui_PanelWaterTemp6;
extern lv_obj_t * ui_LabelTimeS2;
extern lv_obj_t * ui_RollerTimeS2;
extern lv_obj_t * ui_PanelWaterTemp7;
extern lv_obj_t * ui_LabelSuperSpinS2;
extern lv_obj_t * ui_RollerSuperSpinS2;
extern lv_obj_t * ui_PanelWaterTemp8;
extern lv_obj_t * ui_LabelTempS2;
extern lv_obj_t * ui_RollerTempS2;
extern lv_obj_t * ui_PanelLevelS2;
extern lv_obj_t * ui_LabelLevelS2;
extern lv_obj_t * ui_RollerLevelS2;
extern lv_obj_t * ui_PanelSpin;
extern lv_obj_t * ui_LabelSpinS2;
extern lv_obj_t * ui_RollerSpinS2;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel_s3;
void ui_event_PanelDelayS3(lv_event_t * e);
extern lv_obj_t * ui_PanelDelayS3;
extern lv_obj_t * ui_LabelDelayS3;
extern lv_obj_t * ui_RollerDelayS3;
void ui_event_PanelSoakS3(lv_event_t * e);
extern lv_obj_t * ui_PanelSoakS3;
extern lv_obj_t * ui_LabelSoakS3;
extern lv_obj_t * ui_RollerSoakS3;
void ui_event_PanelIronS3(lv_event_t * e);
extern lv_obj_t * ui_PanelIronS3;
extern lv_obj_t * ui_LabelIronS3;
extern lv_obj_t * ui_RollerIronS3;
void ui_event_PanelTubS3(lv_event_t * e);
extern lv_obj_t * ui_PanelTubS3;
extern lv_obj_t * ui_LabelTubS3;
extern lv_obj_t * ui_RollerTubS3;
extern lv_obj_t * ui_ImageIcons3;
extern lv_obj_t * ui_Label_timer_s3;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label16;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * ui_label_control_s1;
extern lv_obj_t * ui_label_controlArabic_s1;
extern lv_obj_t * ui_label_control_s2;
extern lv_obj_t * ui_label_controlArabic_s2;
extern lv_obj_t * ui_label_control_s3;
extern lv_obj_t * ui_label_controlArabic_s3;

LV_IMG_DECLARE(ui_img_1342514607);    // assets\MicrosoftTeams-image (8)(1).png

LV_FONT_DECLARE(ui_font_DSDIGI_40);
LV_FONT_DECLARE(ui_font_DSDIGI_50);
LV_FONT_DECLARE(ui_font_DS_DIGIBOLD_50);
LV_FONT_DECLARE(ui_font_montregular16);
LV_FONT_DECLARE(ui_font_montregular20);
LV_FONT_DECLARE(ui_font_Montregular30);
LV_FONT_DECLARE(ui_font_montregular22);
LV_FONT_DECLARE(ui_font_mont_bold_16);
LV_FONT_DECLARE(ui_font_montbold_22);
LV_FONT_DECLARE(ui_font_nextArabic_20);
LV_FONT_DECLARE(ui_font_nextArabic_16);


extern const char g_str_programs[];
extern const char g_str_waterTemp[];
extern const char g_str_waterLevel[];
extern const char g_str_washTime[];
extern const char g_str_rins[];
extern const char g_str_spin[];
extern const char g_str_superSpin[];


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
