// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: wm_ui

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_s1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_s1, 447);
    lv_obj_set_height(ui_Panel_s1, 187);
    lv_obj_set_x(ui_Panel_s1, -1);
    lv_obj_set_y(ui_Panel_s1, 29);
    lv_obj_set_align(ui_Panel_s1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_s1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel_s1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_s1, lv_color_hex(0x00243C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_s1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_water_level = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_water_level, 112);
    lv_obj_set_height(ui_panel_water_level, 43);
    lv_obj_set_x(ui_panel_water_level, 149);
    lv_obj_set_y(ui_panel_water_level, -7);
    lv_obj_set_align(ui_panel_water_level, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_water_level, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_water_level, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_water_level, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_water_level, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_water_level, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_water_level, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_water_level, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_water_level = lv_dropdown_create(ui_panel_water_level);
    lv_dropdown_set_options(ui_Dropdown_water_level, g_str_waterLevel);
    lv_obj_set_width(ui_Dropdown_water_level, 60);
    lv_obj_set_height(ui_Dropdown_water_level, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_water_level, 2);
    lv_obj_set_y(ui_Dropdown_water_level, -7);
    lv_obj_set_align(ui_Dropdown_water_level, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_water_level, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_water_level, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_water_level, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_water_level, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_water_level, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_water_level, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown_water_level, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_water_level, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_water_level, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_water_level), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_water_level), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_panel_water_level);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 1);
    lv_obj_set_y(ui_Label11, 12);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "WATER LEVEL");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_rins = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_rins, 112);
    lv_obj_set_height(ui_panel_rins, 43);
    lv_obj_set_x(ui_panel_rins, 149);
    lv_obj_set_y(ui_panel_rins, -57);
    lv_obj_set_align(ui_panel_rins, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_rins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_rins, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_rins, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_rins, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_rins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_rins, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_rins, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_rins = lv_dropdown_create(ui_panel_rins);
    lv_dropdown_set_options(ui_Dropdown_rins, g_str_rins);
    lv_obj_set_width(ui_Dropdown_rins, 57);
    lv_obj_set_height(ui_Dropdown_rins, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_rins, 5);
    lv_obj_set_y(ui_Dropdown_rins, -7);
    lv_obj_set_align(ui_Dropdown_rins, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_rins, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_rins, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_rins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_rins, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_rins, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_rins, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown_rins, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_rins, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_rins, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_rins), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_rins), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_panel_rins);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, 12);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "RINS");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller_programs = lv_roller_create(ui_Panel_s1);
    lv_roller_set_options(ui_Roller_programs, g_str_programs,
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller_programs, 134);
    lv_obj_set_width(ui_Roller_programs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_programs, -134);
    lv_obj_set_y(ui_Roller_programs, -7);
    lv_obj_set_align(ui_Roller_programs, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_programs, lv_color_hex(0x9BB7CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_programs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller_programs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller_programs, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Roller_programs, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller_programs, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_programs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_programs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller_programs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller_programs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Roller_programs, 15, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_programs, lv_color_hex(0x005B96), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_programs, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_panel_water_temp = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_water_temp, 112);
    lv_obj_set_height(ui_panel_water_temp, 43);
    lv_obj_set_x(ui_panel_water_temp, 23);
    lv_obj_set_y(ui_panel_water_temp, -57);
    lv_obj_set_align(ui_panel_water_temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_water_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_water_temp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_water_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_water_temp, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_water_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_water_temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_water_temp, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_water_temp = lv_dropdown_create(ui_panel_water_temp);
    lv_dropdown_set_options(ui_Dropdown_water_temp, g_str_waterTemp);
    lv_obj_set_width(ui_Dropdown_water_temp, 45);
    lv_obj_set_height(ui_Dropdown_water_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_water_temp, 0);
    lv_obj_set_y(ui_Dropdown_water_temp, -8);
    lv_obj_set_align(ui_Dropdown_water_temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_water_temp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_water_temp, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_water_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_water_temp, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_water_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_water_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown_water_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_water_temp, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_water_temp, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_water_temp), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_water_temp), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_panel_water_temp);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 12);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WATER TEMP,");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_washtime = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_washtime, 112);
    lv_obj_set_height(ui_panel_washtime, 43);
    lv_obj_set_x(ui_panel_washtime, 23);
    lv_obj_set_y(ui_panel_washtime, -7);
    lv_obj_set_align(ui_panel_washtime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_washtime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_washtime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_washtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_washtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_washtime, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_washtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_washtime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_washtime, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_washtime = lv_dropdown_create(ui_panel_washtime);
    lv_dropdown_set_options(ui_Dropdown_washtime, g_str_washTime);
    lv_obj_set_width(ui_Dropdown_washtime, 57);
    lv_obj_set_height(ui_Dropdown_washtime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_washtime, -2);
    lv_obj_set_y(ui_Dropdown_washtime, -7);
    lv_obj_set_align(ui_Dropdown_washtime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_washtime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_washtime, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_washtime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_washtime, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_washtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_washtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_washtime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_washtime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_washtime, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_washtime, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_washtime), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_washtime), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_Dropdown_washtime), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_Dropdown_washtime), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_Dropdown_washtime), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_Dropdown_washtime), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_panel_washtime);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 1);
    lv_obj_set_y(ui_Label12, 12);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "WASH TIME");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_superspin = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_superspin, 112);
    lv_obj_set_height(ui_panel_superspin, 43);
    lv_obj_set_x(ui_panel_superspin, 23);
    lv_obj_set_y(ui_panel_superspin, 43);
    lv_obj_set_align(ui_panel_superspin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_superspin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_superspin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_superspin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_superspin, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_superspin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_superspin, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_superspin, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_superspin = lv_dropdown_create(ui_panel_superspin);
    lv_dropdown_set_options(ui_Dropdown_superspin, g_str_superSpin);
    lv_obj_set_width(ui_Dropdown_superspin, 57);
    lv_obj_set_height(ui_Dropdown_superspin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_superspin, 4);
    lv_obj_set_y(ui_Dropdown_superspin, -6);
    lv_obj_set_align(ui_Dropdown_superspin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_superspin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_superspin, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_superspin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_superspin, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_superspin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_superspin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown_superspin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_superspin, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_superspin, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_superspin), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_superspin), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_panel_superspin);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 1);
    lv_obj_set_y(ui_Label14, 12);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "SUPER SPIN");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_spin = lv_obj_create(ui_Panel_s1);
    lv_obj_set_width(ui_panel_spin, 112);
    lv_obj_set_height(ui_panel_spin, 43);
    lv_obj_set_x(ui_panel_spin, 149);
    lv_obj_set_y(ui_panel_spin, 43);
    lv_obj_set_align(ui_panel_spin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panel_spin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panel_spin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_spin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_spin, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_spin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_spin, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panel_spin, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown_spin = lv_dropdown_create(ui_panel_spin);
    lv_dropdown_set_options(ui_Dropdown_spin, g_str_spin);
    lv_obj_set_width(ui_Dropdown_spin, 57);
    lv_obj_set_height(ui_Dropdown_spin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_spin, 4);
    lv_obj_set_y(ui_Dropdown_spin, -7);
    lv_obj_set_align(ui_Dropdown_spin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_spin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_spin, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_spin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_spin, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_spin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_spin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown_spin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown_spin, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_spin, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown_spin), lv_color_hex(0xE4E4E4),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown_spin), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_panel_spin);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 1);
    lv_obj_set_y(ui_Label13, 12);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "SPIN");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_timer_s1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label_timer_s1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_timer_s1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_timer_s1, -165);
    lv_obj_set_y(ui_Label_timer_s1, -100);
    lv_obj_set_align(ui_Label_timer_s1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_timer_s1, "00:00");
    lv_obj_set_style_text_color(ui_Label_timer_s1, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_timer_s1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_timer_s1, &ui_font_DSDIGI_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 110);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 104);
    lv_obj_set_y(ui_Button4, 125);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xB3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Options");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x2271A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 110);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -2);
    lv_obj_set_y(ui_Button2, 125);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Edit");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xC6CACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 133);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -118);
    lv_obj_set_y(ui_Button1, 122);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x005B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Program");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xE8F0F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageIconS1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageIconS1, &ui_img_1342514607);
    lv_obj_set_width(ui_ImageIconS1, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_ImageIconS1, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_ImageIconS1, 190);
    lv_obj_set_y(ui_ImageIconS1, -100);
    lv_obj_set_align(ui_ImageIconS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIconS1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIconS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_control_s1 = lv_label_create(ui_Screen1);
    lv_obj_set_align(ui_label_control_s1, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_label_control_s1, 70);
    lv_obj_set_y(ui_label_control_s1, -110);
    lv_obj_set_style_text_font(ui_label_control_s1, &ui_font_montregular20, LV_PART_MAIN);
    lv_label_set_text(ui_label_control_s1, "START / PAUSE");

    ui_label_controlArabic_s1 = lv_label_create(ui_Screen1);
    lv_obj_set_align(ui_label_controlArabic_s1, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_label_controlArabic_s1, 70);
    lv_obj_set_y(ui_label_controlArabic_s1, -90);
    lv_obj_set_style_text_font(ui_label_controlArabic_s1, &ui_font_nextArabic_16, LV_PART_MAIN);
    lv_label_set_text(ui_label_controlArabic_s1, "تشغيل/ إيقاف مؤقت");

    lv_obj_add_event_cb(ui_panel_rins, ui_event_panel_rins, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_panel_water_temp, ui_event_panel_water_temp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller_programs, ui_event_roller_programs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
