// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: wm_ui

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_s3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel_s3, 447);
    lv_obj_set_height(ui_Panel_s3, 187);
    lv_obj_set_x(ui_Panel_s3, -1);
    lv_obj_set_y(ui_Panel_s3, 29);
    lv_obj_set_align(ui_Panel_s3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_s3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel_s3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_s3, lv_color_hex(0x48525A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_s3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDelayS3 = lv_obj_create(ui_Panel_s3);
    lv_obj_set_width(ui_PanelDelayS3, 140);
    lv_obj_set_height(ui_PanelDelayS3, 55);
    lv_obj_set_x(ui_PanelDelayS3, -110);
    lv_obj_set_y(ui_PanelDelayS3, -50);
    lv_obj_set_align(ui_PanelDelayS3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDelayS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDelayS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDelayS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDelayS3 = lv_label_create(ui_PanelDelayS3);
    lv_obj_set_width(ui_LabelDelayS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDelayS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDelayS3, 0);
    lv_obj_set_y(ui_LabelDelayS3, 14);
    lv_obj_set_align(ui_LabelDelayS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDelayS3, "DELAY START");
    lv_obj_add_flag(ui_LabelDelayS3, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelDelayS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDelayS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDelayS3, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerDelayS3 = lv_roller_create(ui_PanelDelayS3);
    lv_roller_set_options(ui_RollerDelayS3, "30 MIN\n1 HOUR\n2 HOURS\n3 HOURS", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerDelayS3, 35);
    lv_obj_set_width(ui_RollerDelayS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerDelayS3, 3);
    lv_obj_set_y(ui_RollerDelayS3, -7);
    lv_obj_set_align(ui_RollerDelayS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerDelayS3, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_color(ui_RollerDelayS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDelayS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerDelayS3, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerDelayS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDelayS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerDelayS3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerDelayS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerDelayS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDelayS3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerDelayS3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerDelayS3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelSoakS3 = lv_obj_create(ui_Panel_s3);
    lv_obj_set_width(ui_PanelSoakS3, 140);
    lv_obj_set_height(ui_PanelSoakS3, 50);
    lv_obj_set_x(ui_PanelSoakS3, -110);
    lv_obj_set_y(ui_PanelSoakS3, 24);
    lv_obj_set_align(ui_PanelSoakS3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSoakS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSoakS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSoakS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSoakS3 = lv_label_create(ui_PanelSoakS3);
    lv_obj_set_width(ui_LabelSoakS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoakS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSoakS3, -2);
    lv_obj_set_y(ui_LabelSoakS3, 14);
    lv_obj_set_align(ui_LabelSoakS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoakS3, "SOAK");
    lv_obj_set_style_text_color(ui_LabelSoakS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSoakS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSoakS3, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerSoakS3 = lv_roller_create(ui_PanelSoakS3);
    lv_roller_set_options(ui_RollerSoakS3, "10 MINS\n20 MINS\n30 MINS", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerSoakS3, 35);
    lv_obj_set_width(ui_RollerSoakS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerSoakS3, 3);
    lv_obj_set_y(ui_RollerSoakS3, -7);
    lv_obj_set_align(ui_RollerSoakS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerSoakS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_EVENT_BUBBLE);      /// Flags
    lv_obj_set_style_text_color(ui_RollerSoakS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerSoakS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerSoakS3, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerSoakS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerSoakS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerSoakS3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerSoakS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerSoakS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerSoakS3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerSoakS3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerSoakS3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelIronS3 = lv_obj_create(ui_Panel_s3);
    lv_obj_set_width(ui_PanelIronS3, 140);
    lv_obj_set_height(ui_PanelIronS3, 50);
    lv_obj_set_x(ui_PanelIronS3, 121);
    lv_obj_set_y(ui_PanelIronS3, 27);
    lv_obj_set_align(ui_PanelIronS3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIronS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelIronS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIronS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_LabelIronS3 = lv_label_create(ui_PanelIronS3);
    lv_obj_set_width(ui_LabelIronS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIronS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIronS3, 1);
    lv_obj_set_y(ui_LabelIronS3, 14);
    lv_obj_set_align(ui_LabelIronS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIronS3, "EASY IRON");
    lv_obj_set_style_text_color(ui_LabelIronS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIronS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIronS3, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerIronS3 = lv_roller_create(ui_PanelIronS3);
    lv_roller_set_options(ui_RollerIronS3, "OFF\nON", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerIronS3, 35);
    lv_obj_set_width(ui_RollerIronS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerIronS3, 3);
    lv_obj_set_y(ui_RollerIronS3, -7);
    lv_obj_set_align(ui_RollerIronS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerIronS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_color(ui_RollerIronS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerIronS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerIronS3, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerIronS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerIronS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerIronS3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerIronS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerIronS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerIronS3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerIronS3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerIronS3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelTubS3 = lv_obj_create(ui_Panel_s3);
    lv_obj_set_width(ui_PanelTubS3, 140);
    lv_obj_set_height(ui_PanelTubS3, 50);
    lv_obj_set_x(ui_PanelTubS3, 119);
    lv_obj_set_y(ui_PanelTubS3, -51);
    lv_obj_set_align(ui_PanelTubS3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTubS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTubS3, lv_color_hex(0xE4E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTubS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTubS3 = lv_label_create(ui_PanelTubS3);
    lv_obj_set_width(ui_LabelTubS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTubS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTubS3, 1);
    lv_obj_set_y(ui_LabelTubS3, 14);
    lv_obj_set_align(ui_LabelTubS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTubS3, "TUB CLEAN");
    lv_obj_set_style_text_color(ui_LabelTubS3, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTubS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTubS3, &ui_font_mont_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerTubS3 = lv_roller_create(ui_PanelTubS3);
    lv_roller_set_options(ui_RollerTubS3, "OFF\nON", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerTubS3, 35);
    lv_obj_set_width(ui_RollerTubS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerTubS3, 3);
    lv_obj_set_y(ui_RollerTubS3, -8);
    lv_obj_set_align(ui_RollerTubS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerTubS3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_EVENT_BUBBLE);      /// Flags
    lv_obj_set_style_text_color(ui_RollerTubS3, lv_color_hex(0x3D80AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTubS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerTubS3, &ui_font_montregular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTubS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTubS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerTubS3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerTubS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerTubS3, lv_color_hex(0x6497B1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTubS3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTubS3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTubS3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ImageIcons3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageIcons3, &ui_img_1342514607);
    lv_obj_set_width(ui_ImageIcons3, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_ImageIcons3, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_ImageIcons3, 190);
    lv_obj_set_y(ui_ImageIcons3, -100);
    lv_obj_set_align(ui_ImageIcons3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIcons3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIcons3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_timer_s3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label_timer_s3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_timer_s3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_timer_s3, -165);
    lv_obj_set_y(ui_Label_timer_s3, -100);
    lv_obj_set_align(ui_Label_timer_s3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_timer_s3, "00:00");
    lv_obj_set_style_text_color(ui_Label_timer_s3, lv_color_hex(0xD0CFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_timer_s3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_timer_s3, &ui_font_DSDIGI_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button9, 130);
    lv_obj_set_height(ui_Button9, 45);
    lv_obj_set_x(ui_Button9, -4);
    lv_obj_set_y(ui_Button9, 123);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x6497B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Edit");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xC6CACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 133);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 105);
    lv_obj_set_y(ui_Button7, 125);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xB3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Options");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x2271A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button8, 110);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -118);
    lv_obj_set_y(ui_Button8, 125);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x005B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button8, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Program");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xE8F0F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button11, 110);
    lv_obj_set_height(ui_Button11, 40);
    lv_obj_set_x(ui_Button11, -25);
    lv_obj_set_y(ui_Button11, -100);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x005B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button11, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button11, &ui_font_montregular22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Program");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xE8F0F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelDelayS3, ui_event_PanelDelayS3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelSoakS3, ui_event_PanelSoakS3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelIronS3, ui_event_PanelIronS3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelTubS3, ui_event_PanelTubS3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
